version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: dj_web
    working_dir: /app
    volumes:
      - ./:/app:cached
    environment:
      - DJANGO_VITE_DEV_MODE=true
      - DJANGO_VITE_DEV_SERVER_HOST=localhost
      - DJANGO_VITE_DEV_SERVER_PORT=5173
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    depends_on:
      - frontend

  frontend:
    image: node:20-alpine
    container_name: dj_frontend
    working_dir: /app/frontend
    command: sh -c "npm ci || npm install && npm run dev -- --host 0.0.0.0"
    volumes:
      - ./:/app:cached
      - /app/frontend/node_modules
    ports:
      - "5173:5173"
